### ISSUE TITLE
Ban System

### ISSUE THREAD

**Issue by TroyKomodo** [ScuffleTV/scuffle#57] opened 2023-02-24 04:36 UTC
Adding the ability to ban and unban people

**Comment by intro23** [comment] 2023-03-14 06:07
For this feature to be complete it implies there are users with `ManageUsers` global role. Should a query to show a users global roles show be included with this?

When banning should we allow for banning multiple users in one request or just one user? 
When banning someone who is already banned what is expected behaviour for each of the cases (banned with `expires_at` set and `expires_at` unset)?

When unbanning should the entry be removed from the table or set the expiration to now?

**Comment by TroyKomodo** [comment] 2023-04-05 00:27
i think the ban system is a bit far without the role system first.
allowing multiple bans vs 1 is an easy change but we need a proper permission system

**Comment by lennartkloock** [comment] 2023-09-04 20:44
Duplicate of #59

**Closed by lennartkloock** 2023-09-04 20:44 UTC
Labels: frontend, backend
